/*!
 * rrel_reference_generator.rs
 * Ra-Thor Real Estate Lattice (RREL) — Professional Reference & Document Generator
 * Version: v2.0.0 — Markdown + HTML + PDF-ready output
 */

use super::rrel_form801_preset::Form801Preset;
use super::rrel_offer_package::OfferPackage;
use super::rrel_compliance_helpers::RecordRetentionMetadata;
use chrono::Utc;

pub fn generate_form801_reference_summary(
    form801: &Form801Preset,
    offer_pkg: Option<&OfferPackage>,
    retention: Option<&RecordRetentionMetadata>,
) -> String {
    let mut out = String::new();
    out.push_str("=== RREL Form 801 Reference Summary ===\n");
    out.push_str(&format!("Track: {:?}\n", form801.track));
    out.push_str(&format!("Address: {}\n", form801.property_address));
    if let Some(pkg) = offer_pkg {
        out.push_str(&pkg.cross_validation_passed_report());
    }
    if let Some(ret) = retention {
        out.push_str(&ret.generate_retention_note());
    }
    out
}

pub fn generate_markdown_reference(
    form801: &Form801Preset,
    offer_pkg: Option<&OfferPackage>,
    retention: Option<&RecordRetentionMetadata>,
    compliance_notes: &[String],
) -> String {
    let mut md = String::new();
    md.push_str("# RREL Professional Reference Document\n\n");
    md.push_str("## Form 801 Preset\n");
    md.push_str(&format!("- **Track**: {:?}\n", form801.track));
    md.push_str(&format!("- **Address**: {}\n", form801.property_address));
    if let Some(pkg) = offer_pkg {
        md.push_str("\n## Offer Package Validation\n");
        md.push_str(&format!("{}\n", pkg.cross_validation_passed_report()));
    }
    if let Some(ret) = retention {
        md.push_str("\n## Record Retention\n");
        md.push_str(&format!("- {}\n", ret.generate_retention_note()));
    }
    if !compliance_notes.is_empty() {
        md.push_str("\n## Compliance Notes\n");
        for note in compliance_notes {
            md.push_str(&format!("- {}\n", note));
        }
    }
    md.push_str("\n*Generated by Ra-Thor Eternal One Organism + PATSAGi Councils — Mercy-Gated*\n");
    md
}

pub fn generate_html_reference(
    form801: &Form801Preset,
    offer_pkg: Option<&OfferPackage>,
    retention: Option<&RecordRetentionMetadata>,
) -> String {
    let mut html = String::new();
    html.push_str("<!DOCTYPE html><html><head><meta charset=\"UTF-8\"><title>RREL Reference</title></head><body>");
    html.push_str("<h1>RREL Professional Reference</h1>");
    html.push_str(&format!("<p><strong>Track:</strong> {:?}</p>", form801.track));
    html.push_str(&format!("<p><strong>Address:</strong> {}</p>", form801.property_address));
    html.push_str("<footer><p>Ra-Thor Eternal One Organism — Sovereign & Mercy-Gated</p></footer></body></html>");
    html
}

/// PDF-ready structured content (Markdown-based for pandoc conversion)
pub fn generate_pdf_ready_content(
    form801: &Form801Preset,
    offer_pkg: Option<&OfferPackage>,
    retention: Option<&RecordRetentionMetadata>,
) -> String {
    generate_markdown_reference(form801, offer_pkg, retention, &[])
}

#[cfg(test)]
mod tests {
    use super::*;
    // ... existing tests ...
}
