//! # Monorepo Report Generator
//!
//! Generates beautiful, structured reports from monorepo scans.
//! Especially useful for Powrush, crate health, and overall system status.

use crate::scanner::{ScanResult, ScannedFile};
use chrono::{DateTime, Utc};
use serde::{Serialize, Deserialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MonorepoReport {
    pub generated_at: DateTime<Utc>,
    pub total_files: usize,
    pub total_directories: usize,
    pub total_size_mb: f64,
    pub keyword: Option<String>,
    pub matching_files: Vec<ScannedFile>,
    pub summary: String,
}

impl MonorepoReport {
    pub fn from_scan(scan: &ScanResult, keyword: Option<&str>) -> Self {
        let matching_files: Vec<ScannedFile> = if let Some(kw) = keyword {
            scan.files
                .iter()
                .filter(|f| {
                    f.relative_path.to_lowercase().contains(&kw.to_lowercase())
                        || f.path.to_lowercase().contains(&kw.to_lowercase())
                })
                .cloned()
                .collect()
        } else {
            vec![]
        };

        let total_size_mb = scan.total_size_bytes as f64 / 1_048_576.0;

        let summary = if let Some(kw) = keyword {
            format!(
                "Found {} files matching '{}' across {} directories. Total repository size: {:.2} MB.",
                matching_files.len(),
                kw,
                scan.total_directories,
                total_size_mb
            )
        } else {
            format!(
                "Monorepo contains {} files and {} directories. Total size: {:.2} MB.",
                scan.total_files,
                scan.total_directories,
                total_size_mb
            )
        };

        Self {
            generated_at: Utc::now(),
            total_files: scan.total_files,
            total_directories: scan.total_directories,
            total_size_mb,
            keyword: keyword.map(|s| s.to_string()),
            matching_files,
            summary,
        }
    }

    /// Generate a beautiful Markdown report
    pub fn to_markdown(&self) -> String {
        let mut md = String::new();

        md.push_str("# Ra-Thor Monorepo Report\n\n");
        md.push_str(&format!("**Generated:** {}\n\n", self.generated_at));

        if let Some(kw) = &self.keyword {
            md.push_str(&format!("## Search Results for: `{}`\n\n", kw));
        } else {
            md.push_str("## Monorepo Overview\n\n");
        }

        md.push_str(&format!("- **Total Files:** {}\n", self.total_files));
        md.push_str(&format!("- **Total Directories:** {}\n", self.total_directories));
        md.push_str(&format!("- **Total Size:** {:.2} MB\n\n", self.total_size_mb));

        md.push_str(&format!("**Summary:** {}\n\n", self.summary));

        if !self.matching_files.is_empty() {
            md.push_str("## Matching Files\n\n");
            for file in &self.matching_files {
                md.push_str(&format!(
                    "- `{}` ({})\n",
                    file.relative_path,
                    if file.is_dir { "Directory" } else { "File" }
                ));
            }
        }

        md.push_str("\n---\n*Generated by Ra-Thor Monorepo Intelligence*\n");
        md
    }

    /// Generate JSON report
    pub fn to_json(&self) -> Result<String, String> {
        serde_json::to_string_pretty(self).map_err(|e| e.to_string())
    }
}
