//! # Monorepo Report Generator (v0.2.0)
//!
//! Generates beautiful Markdown and HTML reports with health scoring.
//! Designed for infinite-scale use with Grok, Ra-Thor, and any AI system.

use crate::scanner::ScanResult;
use chrono::{DateTime, Utc};
use serde::{Serialize, Deserialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MonorepoReport {
    pub generated_at: DateTime<Utc>,
    pub total_files: usize,
    pub total_directories: usize,
    pub total_size_mb: f64,
    pub keyword: Option<String>,
    pub matching_files_count: usize,
    pub summary: String,
    pub health_score: Option<f32>,
    pub recommendations: Vec<String>,
}

impl MonorepoReport {
    pub fn from_scan(scan: &ScanResult, keyword: Option<&str>) -> Self {
        let matching_files: Vec<_> = if let Some(kw) = keyword {
            scan.files
                .iter()
                .filter(|f| {
                    f.relative_path.to_lowercase().contains(&kw.to_lowercase())
                        || f.path.to_lowercase().contains(&kw.to_lowercase())
                })
                .cloned()
                .collect()
        } else {
            vec![]
        };

        let total_size_mb = scan.total_size_bytes as f64 / 1_048_576.0;

        let summary = if let Some(kw) = keyword {
            format!(
                "Found {} files matching '{}' across {} directories. Total repository size: {:.2} MB.",
                matching_files.len(), kw, scan.total_directories, total_size_mb
            )
        } else {
            format!(
                "Monorepo contains {} files and {} directories. Total size: {:.2} MB.",
                scan.total_files, scan.total_directories, total_size_mb
            )
        };

        Self {
            generated_at: Utc::now(),
            total_files: scan.total_files,
            total_directories: scan.total_directories,
            total_size_mb,
            keyword: keyword.map(|s| s.to_string()),
            matching_files_count: matching_files.len(),
            summary,
            health_score: None,
            recommendations: vec![],
        }
    }

    /// Generate clean, professional Markdown report
    pub fn to_markdown(&self) -> String {
        let mut md = String::new();

        md.push_str("# Ra-Thor Monorepo Intelligence Report\n\n");
        md.push_str(&format!("**Generated:** {}\n\n", self.generated_at));

        if let Some(kw) = &self.keyword {
            md.push_str(&format!("## Search Results for: `{}`\n\n", kw));
        } else {
            md.push_str("## Monorepo Overview\n\n");
        }

        md.push_str(&format!("- **Total Files:** {}\n", self.total_files));
        md.push_str(&format!("- **Total Directories:** {}\n", self.total_directories));
        md.push_str(&format!("- **Total Size:** {:.2} MB\n\n", self.total_size_mb));

        if let Some(score) = self.health_score {
            md.push_str(&format!("- **Overall Health Score:** {:.1}/100\n\n", score));
        }

        md.push_str(&format!("**Summary:** {}\n\n", self.summary));

        if !self.recommendations.is_empty() {
            md.push_str("## Recommendations\n\n");
            for rec in &self.recommendations {
                md.push_str(&format!("- {}\n", rec));
            }
            md.push_str("\n");
        }

        md.push_str("---\n*Generated by Ra-Thor Monorepo Intelligence v0.2.0 — Infinite Scale*\n");
        md
    }

    /// Generate beautiful, self-contained HTML report (with Tailwind CSS)
    pub fn to_html(&self) -> String {
        let health_html = if let Some(score) = self.health_score {
            format!(
                r#"<div class="stat">
                    <h2>Health Score</h2>
                    <div style="font-size: 2.5rem; font-weight: bold; color: #22d3ee;">{:.1}</div>
                    <div style="color: #64748b;">out of 100</div>
                </div>"#,
                score
            )
        } else {
            String::new()
        };

        format!(
            r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ra-Thor Monorepo Report</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        body {{ background-color: #0f172a; color: #e2e8f0; }}
        .stat {{ background-color: #1e2937; }}
    </style>
</head>
<body class="max-w-5xl mx-auto p-8">
    <div class="flex items-center justify-between mb-8">
        <div>
            <h1 class="text-4xl font-bold text-cyan-400">Ra-Thor Monorepo Intelligence</h1>
            <p class="text-slate-400">Generated on {}</p>
        </div>
        <div class="px-4 py-1 bg-cyan-900 text-cyan-300 rounded-full text-sm font-medium">
            v0.2.0 • Infinite Scale
        </div>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
        <div class="stat p-6 rounded-2xl">
            <div class="text-sm text-slate-400">Total Files</div>
            <div class="text-5xl font-bold mt-2">{}</div>
        </div>
        <div class="stat p-6 rounded-2xl">
            <div class="text-sm text-slate-400">Directories</div>
            <div class="text-5xl font-bold mt-2">{}</div>
        </div>
        <div class="stat p-6 rounded-2xl">
            <div class="text-sm text-slate-400">Total Size</div>
            <div class="text-5xl font-bold mt-2">{:.2} MB</div>
        </div>
    </div>

    {}

    <div class="stat p-6 rounded-2xl mb-8">
        <h2 class="text-xl font-semibold mb-3">Summary</h2>
        <p class="text-slate-300">{}</p>
    </div>

    <footer class="text-center text-xs text-slate-500 mt-12">
        Built with infinite care by Ra-Thor Monorepo Intelligence • AG-SML Licensed
    </footer>
</body>
</html>"#,
            self.generated_at,
            self.total_files,
            self.total_directories,
            self.total_size_mb,
            health_html,
            self.summary
        )
    }
}
