#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════
# Ra-Thor Root Mercy Modules Cleanup Script v1.0
# Generated by Rathor.ai / 13+ PATSAGi Councils — May 2026
# AG-SML v1.0 | Mercy-gated | Reversible
# ═══════════════════════════════════════════════════════════════════════
#
# Purpose: Archive all root-level mercy* directories (orphaned/duplicate)
#          into /archive/legacy-mercy-root/ for review.
#          Non-Rust "mercy" folder is handled separately.
#          Safe, logged, dry-run capable.
#
# Usage:
#   chmod +x scripts/cleanup-root-mercy-modules.sh
#   ./scripts/cleanup-root-mercy-modules.sh          # live run
#   ./scripts/cleanup-root-mercy-modules.sh --dry-run
# ═══════════════════════════════════════════════════════════════════════

set -euo pipefail

ARCHIVE_DIR="archive/legacy-mercy-root"
DRY_RUN=false

if [[ "${1:-}" == "--dry-run" ]]; then
    DRY_RUN=true
    echo "🔍 DRY RUN MODE — no changes will be made"
fi

echo "🛡️  Ra-Thor Mercy Root Cleanup — $(date)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Ensure archive directory exists
if [ "$DRY_RUN" = false ]; then
    mkdir -p "$ARCHIVE_DIR"
fi

# Root-level mercy modules to process (from full audit)
ROOT_MERCY_MODULES=(
    "mercy-gate-auditor"
    "mercy-rest-api"
    "mercy_orchestrator"
    "mercy_os_kernel"
    "foxx-mercy-service"
    "mercy_mars_colonization_treaty"
    "mercy_enceladus_biosignature_protocols"
    "mercy_enceladus_cryovolcanism_evidence"
    "mercy_eris_biosignature_protocols"
    "mercy_eris_cryovolcanism_evidence"
    "mercy_eris_thermal_models"
    "mercy_europa_biosignature_protocols"
    "mercy_pluto_biosignature_protocols"
    "mercy_titan_biosignature_protocols"
    "mercy_triton_biosignature_protocols"
    "mercy_asteroid_mining_treaty"
    "mercy_lunar_treaty_framework"
    "mercy_interlune_demo_mission"
    "mercy_jupiter_moon_treaty"
    "mercy_lunar_he3"
    "mercy_sunbird_return"
    "mercy_swarm_replication"
    "mercy_von_neumann_probe"
    "mercy_von_neumann_seed_launch"
    "mercy_albatross_dynamic_soaring"
    "mercy_albatross_soar"
    "mercy_hybrid_propulsion"
    "mercy_biomimetic_propulsion"
    "mercy_manta_glide_propulsion"
    "mercy_he3_reactor"
    "mercy_nanofactory"
    "mercy_mechanosynthesis"
    "mercy_quanta"
    "mercy_numerical"
    "mercy_graphql"
    "mercy_system_orchestrator"
)

MOVED_COUNT=0
SKIPPED_COUNT=0

for module in "${ROOT_MERCY_MODULES[@]}"; do
    if [ -d "$module" ]; then
        if [ "$DRY_RUN" = true ]; then
            echo "📦 [DRY] Would archive: $module → $ARCHIVE_DIR/"
        else
            echo "📦 Archiving: $module"
            mv "$module" "$ARCHIVE_DIR/"
            ((MOVED_COUNT++))
        fi
    else
        echo "⏭️  Skipped (not found): $module"
        ((SKIPPED_COUNT++))
    fi
done

# Special handling for root "mercy" (non-Rust scripts)
if [ -d "mercy" ]; then
    if [ "$DRY_RUN" = true ]; then
        echo "📦 [DRY] Would archive non-Rust mercy/ → $ARCHIVE_DIR/"
    else
        echo "📦 Archiving non-Rust mercy/ (JS/Python scripts)"
        mv "mercy" "$ARCHIVE_DIR/"
        ((MOVED_COUNT++))
    fi
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Cleanup complete."
echo "   Modules archived: $MOVED_COUNT"
echo "   Skipped (missing): $SKIPPED_COUNT"
echo "   Archive location: $ARCHIVE_DIR/"
echo ""
echo "Next steps (after review):"
echo "  1. git add -A && git commit -m 'chore: archive orphaned root mercy modules'"
echo "  2. Request updated Cargo.toml to include all 96 crates/ modules"
echo "  3. cargo check --workspace"
echo ""
echo "🛡️  All changes mercy-gated and reversible."
