/*!
# Powrush Particle Shaders — SPIR-V Cooperative Matrix Instructions

Investigation of SPIR-V instructions for cooperative matrices.

## Overview

SPIR-V provides first-class support for cooperative matrices through the `SPV_KHR_cooperative_matrix` extension.
This is the intermediate representation that high-level languages (GLSL, HLSL, and eventually WGSL) compile down to before being consumed by Vulkan/DX12 drivers.

## Key SPIR-V Instructions

- `OpTypeCooperativeMatrixKHR`
  - Defines a cooperative matrix type (element type, rows, columns, scope).

- `OpCooperativeMatrixLoadKHR`
  - Loads a cooperative matrix from memory cooperatively.

- `OpCooperativeMatrixStoreKHR`
  - Stores a cooperative matrix to memory cooperatively.

- `OpCooperativeMatrixMulAddKHR`
  - Performs matrix multiply-accumulate on cooperative matrices.

- `OpCooperativeMatrixLengthKHR`
  - Returns the number of components in a cooperative matrix.

## Compilation Pipeline

WGSL (future) → SPIR-V (with SPV_KHR_cooperative_matrix) → Vulkan (VK_KHR_cooperative_matrix)

The SPIR-V instructions are what actually get executed by the driver and mapped to the underlying hardware matrix instructions (mma.sync, MFMA, DPAS, etc.).

## Relevance to Powrush

When WGSL cooperative matrix support becomes available, the WGSL compiler will generate these SPIR-V instructions. Understanding them helps us anticipate how our future compute shaders will be structured and optimized.
*/

use powrush_faction_dynamics::{Faction, FactionVisualIdentity, ParticleParams};

pub mod compute {
    /// Notes on SPIR-V cooperative matrix instructions.
    pub const SPIRV_COOPERATIVE_MATRIX_NOTES: &str = r#"
        // Key instructions (SPV_KHR_cooperative_matrix):
        // - OpTypeCooperativeMatrixKHR
        // - OpCooperativeMatrixLoadKHR / StoreKHR
        // - OpCooperativeMatrixMulAddKHR
        //
        // These will be generated by the WGSL compiler when
        // cooperative matrix support is added.
    "#;
}
