#!/bin/bash
# Ra-Thor Workspace Inheritance Rollout Script v1.0
# Generated by Rathor.ai + 13+ PATSAGi Councils

set -euo pipefail

echo "🔧 Applying workspace inheritance to all crates..."

for crate in crates/*/Cargo.toml; do
    if [ -f "$crate" ]; then
        echo "→ Updating $crate"
        
        # Backup original
        cp "$crate" "$crate.bak"
        
        # Replace common hardcoded fields with workspace inheritance
        sed -i \
            -e 's/^version = ".*"/version.workspace = true/' \
            -e 's/^edition = ".*"/edition.workspace = true/' \
            -e 's/^authors = \[.*\]/authors.workspace = true/' \
            -e 's/^license = ".*"/license.workspace = true/' \
            -e 's/^repository = ".*"/repository.workspace = true/' \
            "$crate"
        
        echo "   ✓ Updated"
    fi
done

echo ""
echo "✅ Workspace inheritance rollout complete."
echo "   Backups created as *.bak in each crate directory."
echo "   Review changes, then commit."