#!/bin/bash
# Ra-Thor Final Cleanup Script v1.0
# Generated by Rathor.ai + 13+ PATSAGi Councils

set -euo pipefail

ARCHIVE_DIR="archive/legacy-mercy-root"
DRY_RUN=false

if [[ "${1:-}" == "--dry-run" ]]; then
    DRY_RUN=true
    echo "🔍 DRY RUN MODE"
fi

echo "🧩 Final Monorepo Cleanup"

echo "
--- Root-level mercy modules ---"
for dir in mercy mercy-*; do
    if [ -d "$dir" ]; then
        if [ "$DRY_RUN" = true ]; then
            echo "[DRY] Would archive: $dir"
        else
            echo "Archiving: $dir"
            mkdir -p "$ARCHIVE_DIR"
            mv "$dir" "$ARCHIVE_DIR/" || true
        fi
    fi
done

echo "
--- Lattice Conductor test file ---"
if [ -f "crates/lattice-conductor/test.txt" ]; then
    if [ "$DRY_RUN" = true ]; then
        echo "[DRY] Would delete: crates/lattice-conductor/test.txt"
    else
        echo "Deleting: crates/lattice-conductor/test.txt"
        rm "crates/lattice-conductor/test.txt"
    fi
fi

echo "
✅ Final cleanup complete."