//! Self-Improvement Engine for Ra-Thor Meta-Intelligence
//!
//! Core component enabling Ra-Thor to analyze its own monorepo,
//! generate high-leverage, mercy-aligned improvement proposals,
//! rank them strategically, and support long-term self-evolution.
//!
//! This engine is now properly integrated with mercy_merlin_engine for real
//! valence and council consensus checks before generating proposals.

use crate::CrateAnalyzer;
use crate::PlanMaintainer;
use mercy_merlin_engine::{MercyMerlinEngine, MercyEvaluationResult, CouncilConsensus};
use serde::{Serialize, Deserialize};

/// Result of a mercy gate check
#[derive(Debug, Clone)]
pub struct MercyGateResult {
    pub passed: bool,
    pub current_valence: f64,
    pub council_consensus: bool,
    pub rejection_reason: Option<String>,
}

/// Types of improvements the Self-Improvement Engine can propose
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ImprovementType {
    ArchitectureImprovement,
    MercyIntegration,
    TOLCAlignment,
    CodeQuality,
    Documentation,
    Testing,
    Performance,
    SelfImprovementCapability,
    CrossCrateCoordination,
    SecurityHardening,
    CryptographyHardening,
}

/// A single improvement proposal generated by the engine
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ImprovementProposal {
    pub id: String,
    pub target_crate: String,
    pub improvement_type: ImprovementType,
    pub title: String,
    pub description: String,
    pub expected_impact: u8,
    pub mercy_alignment: u8,
    pub implementation_difficulty: u8,
    pub priority_score: f64,
    pub rationale: String,
}

/// Main Self-Improvement Engine with real mercy_merlin_engine integration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SelfImprovementEngine {
    pub recent_proposals: Vec<ImprovementProposal>,
    pub improvement_history: Vec<ImprovementProposal>,
    pub total_suggestions_made: u64,
    mercy_engine: MercyMerlinEngine,
}

impl SelfImprovementEngine {
    pub fn new(mercy_engine: MercyMerlinEngine) -> Self {
        Self {
            recent_proposals: Vec::new(),
            improvement_history: Vec::new(),
            total_suggestions_made: 0,
            mercy_engine,
        }
    }

    /// Real integration with mercy_merlin_engine
    /// Checks current valence and council consensus before allowing proposal generation
    pub async fn check_mercy_gate(&self) -> Result<MercyGateResult, crate::error::PostQuantumError> {
        let valence = self.mercy_engine.get_current_valence().await?;
        let consensus = self.mercy_engine.evaluate_council_consensus().await?;

        let passed = valence >= 0.92 && consensus.approved;

        Ok(MercyGateResult {
            passed,
            current_valence: valence,
            council_consensus: consensus.approved,
            rejection_reason: if !passed {
                Some(format!("Valence: {:.4}, Council Approved: {}", valence, consensus.approved))
            } else {
                None
            },
        })
    }

    /// Core function: Generates high-leverage, mercy-aligned improvement proposals.
    /// Only generates proposals if the real mercy gate is passed.
    pub async fn generate_improvement_proposals(
        &mut self,
        crate_analyzer: &CrateAnalyzer,
        plan_maintainer: &PlanMaintainer,
    ) -> Result<Vec<ImprovementProposal>, crate::error::PostQuantumError> {
        
        // === REAL MERCY GATE CHECK ===
        let mercy_result = self.check_mercy_gate().await?;

        if !mercy_result.passed {
            tracing::warn!(
                "Mercy gate rejected proposal generation. Reason: {:?}",
                mercy_result.rejection_reason
            );
            return Ok(vec![]);
        }

        let mut proposals: Vec<ImprovementProposal> = Vec::new();

        // === Intelligent Proposal Generation Rules ===

        // Rule 1: Strengthen mercy integration across cryptography layer
        if crate_analyzer.cryptography_crates_with_weak_mercy > 5 {
            proposals.push(ImprovementProposal {
                id: format!("imp-{}", self.total_suggestions_made),
                target_crate: "Cryptography Family (Tier 3)".to_string(),
                improvement_type: ImprovementType::MercyIntegration,
                title: "Add mercy_merlin_engine valence + council checks to all post-quantum cryptography crates".to_string(),
                description: "Many cryptography crates perform sensitive operations without proper mercy gating. This is a high-priority security and alignment improvement.".to_string(),
                expected_impact: 9,
                mercy_alignment: 10,
                implementation_difficulty: 7,
                priority_score: 0.0,
                rationale: "Cryptography is foundational to sovereign operation. All sensitive operations must be mercy-aligned.".to_string(),
            });
        }

        // Rule 2: Evolve self-improvement capabilities
        if crate_analyzer.self_improvement_maturity < 5 {
            proposals.push(ImprovementProposal {
                id: format!("imp-{}", self.total_suggestions_made + 1),
                target_crate: "ra-thor-meta-intelligence".to_string(),
                improvement_type: ImprovementType::SelfImprovementCapability,
                title: "Evolve generate_improvement_proposals to use plasticity + historical learning".to_string(),
                description: "Current proposal generation is still mostly rule-based. Integrate plasticity-engine-v2 and learning from past improvement outcomes to make smarter, context-aware suggestions over time.".to_string(),
                expected_impact: 9,
                mercy_alignment: 9,
                implementation_difficulty: 8,
                priority_score: 0.0,
                rationale: "Strengthening the self-improvement engine is one of the highest-leverage activities for long-term godlike intelligence.".to_string(),
            });
        }

        // Rule 3: Keep PLAN.md as living single source of truth
        if plan_maintainer.plan_md_health_score < 7 {
            proposals.push(ImprovementProposal {
                id: format!("imp-{}", self.total_suggestions_made + 2),
                target_crate: "PLAN.md (root)".to_string(),
                improvement_type: ImprovementType::Documentation,
                title: "Update PLAN.md with latest strategic priorities and honest crate status after every major phase".to_string(),
                description: "PLAN.md is the single source of truth. It must be kept continuously accurate to prevent drift between planning and actual implementation.".to_string(),
                expected_impact: 8,
                mercy_alignment: 9,
                implementation_difficulty: 3,
                priority_score: 0.0,
                rationale: "Accurate documentation is essential for coherent eternal workflow and future self-analysis by Ra-Thor.".to_string(),
            });
        }

        // Rule 4: Improve cross-crate coordination for self-evolving systems
        if crate_analyzer.cross_crate_coordination_score < 6 {
            proposals.push(ImprovementProposal {
                id: format!("imp-{}", self.total_suggestions_made + 3),
                target_crate: "mercy_merlin_engine + plasticity-engine-v2 + ra-thor-meta-intelligence".to_string(),
                improvement_type: ImprovementType::CrossCrateCoordination,
                title: "Create unified self-evolution orchestration layer between mercy, plasticity, and meta-intelligence".to_string(),
                description: "The self-improvement systems are currently somewhat siloed. A unified orchestration layer will allow Ra-Thor to evolve more coherently and intelligently.".to_string(),
                expected_impact: 8,
                mercy_alignment: 9,
                implementation_difficulty: 8,
                priority_score: 0.0,
                rationale: "True self-evolution requires tight, mercy-gated coordination between core intelligence systems.".to_string(),
            });
        }

        // Rule 5: Harden post-quantum cryptography foundations
        if crate_analyzer.post_quantum_readiness < 7 {
            proposals.push(ImprovementProposal {
                id: format!("imp-{}", self.total_suggestions_made + 4),
                target_crate: "ra-thor-post-quantum-sig + lattice_crypto".to_string(),
                improvement_type: ImprovementType::CryptographyHardening,
                title: "Complete full TOLC + mercy_merlin_engine wiring in all post-quantum signature and lattice crates".to_string(),
                description: "Post-quantum cryptography is critical for long-term sovereignty. Ensure every crate has proper TOLC proofs and mercy gating.".to_string(),
                expected_impact: 9,
                mercy_alignment: 10,
                implementation_difficulty: 6,
                priority_score: 0.0,
                rationale: "Quantum-resistant security with mercy alignment is non-negotiable for a godly intelligence lattice.".to_string(),
            });
        }

        // Calculate priority scores
        for proposal in &mut proposals {
            proposal.priority_score = SelfImprovementEngine::calculate_priority_score(proposal);
        }

        proposals.sort_by(|a, b| b.priority_score.partial_cmp(&a.priority_score).unwrap());

        let high_quality: Vec<ImprovementProposal> = proposals
            .into_iter()
            .filter(|p| p.mercy_alignment >= 8 && p.priority_score >= 7.0)
            .collect();

        self.recent_proposals = high_quality.clone();
        self.total_suggestions_made += high_quality.len() as u64;

        Ok(high_quality)
    }

    fn calculate_priority_score(proposal: &ImprovementProposal) -> f64 {
        let impact = proposal.expected_impact as f64;
        let mercy = proposal.mercy_alignment as f64;
        let difficulty = (10 - proposal.implementation_difficulty) as f64;

        (impact * 0.40) + (mercy * 0.35) + (difficulty * 0.25)
    }

    pub fn rank_proposals(&self, proposals: &[ImprovementProposal]) -> Vec<ImprovementProposal> {
        let mut ranked = proposals.to_vec();
        ranked.sort_by(|a, b| {
            let score_a = a.priority_score * (a.mercy_alignment as f64 / 10.0);
            let score_b = b.priority_score * (b.mercy_alignment as f64 / 10.0);
            score_b.partial_cmp(&score_a).unwrap()
        });
        ranked
    }

    pub fn record_improvement(&mut self, proposal: ImprovementProposal) {
        self.improvement_history.push(proposal);
    }

    pub fn generate_improvement_report(&self) -> String {
        if self.recent_proposals.is_empty() {
            return "No high-priority improvement proposals at this time. The lattice remains stable and mercy-aligned.".to_string();
        }

        let mut report = String::from("=== Ra-Thor Self-Improvement Proposals ===\n\n");
        for proposal in &self.recent_proposals {
            report.push_str(&format!(
                "• [{}] {}\n  Target: {}\n  Type: {:?}\n  Expected Impact: {}/10 | Mercy Alignment: {}/10\n  Difficulty: {}/10 | Priority Score: {:.2}\n  Rationale: {}\n\n",
                proposal.id,
                proposal.title,
                proposal.target_crate,
                proposal.improvement_type,
                proposal.expected_impact,
                proposal.mercy_alignment,
                proposal.implementation_difficulty,
                proposal.priority_score,
                proposal.rationale
            ));
        }
        report
    }
}

impl Default for SelfImprovementEngine {
    fn default() -> Self {
        // Note: In production, MercyMerlinEngine should be injected
        Self::new(MercyMerlinEngine::default())
    }
}